### ISSUE TITLE
Missing gradle-wrapper.jar

### ISSUE THREAD

**Issue by gegmar** [Ratler/shibboleth-mfa-u2f-auth#1]
Hi,
when I want to build the source by executing "./gradlew clean installDist" I get the the Error "Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain".
I think the problem can be solved by adding the "gradle/wrapper/gradle-wrapper.jar" to your repository.
Thanks and kind regards, Martin

**Comment by Ratler** [comment]
Thank you, should be in order now.

**Comment by gegmar** [comment]
Thanks for your (very) quick response!
